PART 1: THEORETICAL QUESTIONS

1. What are the different data structures used in tensorflow?Give some examples

TensorFlow, a popular machine learning framework, utilizes various data structures to efficiently handle and process data. Here are some of the key data structures:

### 1. Tensors
- **Description**: The primary data structure in TensorFlow. Tensors are multi-dimensional arrays with a uniform type (such as `float32` or `int32`).
- **Examples**:
  ```python
  import tensorflow as tf
  # A scalar
  scalar = tf.constant(3.0, dtype=tf.float32)
  
  # A vector
  vector = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
  
  # A matrix
  matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
  
  # A 3-D tensor
  tensor_3d = tf.constant([[[1.0], [2.0]], [[3.0], [4.0]]], dtype=tf.float32)
  ```

### 2. Variables
- **Description**: Tensors that can be modified by running operations on them. Used to store model parameters.
- **Examples**:
  ```python
  # Create a variable
  var = tf.Variable(3.0, dtype=tf.float32)
  
  # Update the variable
  var.assign(4.0)
  ```

### 3. Sparse Tensors
- **Description**: Efficiently represent tensors with a large proportion of zero values.
- **Examples**:
  ```python
  # Create a sparse tensor
  sparse_tensor = tf.SparseTensor(indices=[[0, 0], [1, 2]],
                                  values=[1, 2],
                                  dense_shape=[3, 4])
  ```

### 4. Ragged Tensors
- **Description**: Used to handle tensors with variable length dimensions.
- **Examples**:
  ```python
  # Create a ragged tensor
  ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
  ```

### 5. DataSet API
- **Description**: Provides a way to build input pipelines to efficiently handle data loading and preprocessing.
- **Examples**:
  ```python
  # Create a dataset from a tensor
  dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
  
  # Create a dataset from a generator
  def gen():
      for i in range(6, 11):
          yield i
  
  dataset_from_gen = tf.data.Dataset.from_generator(gen, output_types=tf.int32)
  ```

### 6. Queues
- **Description**: Used in TensorFlow 1.x for creating input pipelines. In TensorFlow 2.x, the `tf.data` API is preferred.
- **Examples**:
  ```python
  import tensorflow.compat.v1 as tf1
  tf1.disable_v2_behavior()
  
  # FIFOQueue
  queue = tf1.FIFOQueue(capacity=10, dtypes=tf.int32)
  enqueue_op = queue.enqueue([1])
  ```

### 7. Maps and Sets (in tf.data)
- **Description**: Used for efficient data transformations and lookup operations within input pipelines.
- **Examples**:
  ```python
  # Use map function to transform dataset elements
  dataset = dataset.map(lambda x: x * 2)
  ```

2. How does the tensorflow constant differ from a tensorflow variable? Explain with example

In TensorFlow, constants and variables are both fundamental data structures, but they serve different purposes in computational graphs. Here’s how they differ:

### TensorFlow Constant:
- **Purpose**: Constants are tensors whose values cannot be changed once they are defined. They are used for storing values that remain constant throughout the execution of a computational graph.
- **Example**:
  ```python
  import tensorflow as tf
  
  # Define a constant tensor
  constant_tensor = tf.constant([1.0, 2.0, 3.0])
  ```

- **Key Points**:
  - Values are set when the constant is defined and cannot be modified.
  - Constants are typically used for values like hyperparameters, fixed weights, or any value that remains unchanged during computation.

### TensorFlow Variable:
- **Purpose**: Variables are mutable tensors that can be modified during the execution of a computational graph. They are typically used to hold and update model parameters, such as weights and biases, during training.
- **Example**:
  ```python
  import tensorflow as tf
  
  # Define a variable tensor
  initial_value = tf.random.normal(shape=(3,))
  variable_tensor = tf.Variable(initial_value)
  ```

- **Key Points**:
  - Variables must be explicitly initialized before they can be used.
  - Their values can be changed using operations like `assign` or `assign_add`, making them suitable for storing and updating model parameters during training.
  - Variables are crucial in machine learning models where parameters need to be adjusted iteratively based on the training data.


3. Describe process of matrix addition, multiplication and element-wise operations in tensorflow.

In TensorFlow, matrix operations such as addition, multiplication, and element-wise operations are fundamental for building and manipulating computational graphs, especially in the context of machine learning and deep learning models. Here’s a description of each process:

### 1. Matrix Addition

Matrix addition in TensorFlow involves adding corresponding elements of two matrices of the same shape.

- **Example**:
  ```python
  import tensorflow as tf
  
  # Define two matrices
  A = tf.constant([[1, 2], [3, 4]])
  B = tf.constant([[5, 6], [7, 8]])
  
  # Matrix addition
  C = tf.add(A, B)
  
  # Run a TensorFlow session to compute the result
  with tf.Session() as sess:
      result = sess.run(C)
      print(result)
  ```

- **Output**:
  ```
  [[ 6  8]
   [10 12]]
  ```

### 2. Matrix Multiplication

Matrix multiplication in TensorFlow follows the standard linear algebra rules, where the number of columns in the first matrix must equal the number of rows in the second matrix.

- **Example**:
  ```python
  import tensorflow as tf
  
  # Define two matrices
  A = tf.constant([[1, 2], [3, 4]])
  B = tf.constant([[5, 6], [7, 8]])
  
  # Matrix multiplication
  C = tf.matmul(A, B)
  
  # Run a TensorFlow session to compute the result
  with tf.Session() as sess:
      result = sess.run(C)
      print(result)
  ```

- **Output**:
  ```
  [[19 22]
   [43 50]]
  ```

### 3. Element-wise Operations

Element-wise operations in TensorFlow involve applying an operation (like addition, multiplication, etc.) independently to each element of one or more tensors.

- **Example**:
  ```python
  import tensorflow as tf
  
  # Define two matrices
  A = tf.constant([[1, 2], [3, 4]])
  B = tf.constant([[5, 6], [7, 8]])
  
  # Element-wise multiplication
  C = tf.multiply(A, B)  # Can also use A * B
  
  # Run a TensorFlow session to compute the result
  with tf.Session() as sess:
      result = sess.run(C)
      print(result)
  ```

- **Output**:
  ```
  [[ 5 12]
   [21 32]]
  ```

PART 2 : PRACTICAL IMPLEMENTATION

TASK1 : Creating and manipulating matrices

1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.
2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [2]:
# 1. Create a normal matrix A with dimensions 3x3
import tensorflow as tf
A = tf.random.normal(shape=(3, 3))
print("Matrix A (3x3) with normal distribution:")
print(A.numpy())
print()

Matrix A (3x3) with normal distribution:
[[-0.7449132  -0.43666938 -0.1639414 ]
 [-0.21202825  0.39406496 -0.13202423]
 [ 0.3187002   0.30856046 -2.100169  ]]



In [3]:
# 2. Create a Gaussian matrix B with dimensions 4x4
B = tf.random.truncated_normal(shape=(4, 4))
print("Matrix B (4x4) with truncated normal distribution:")
print(B.numpy())
print()

Matrix B (4x4) with truncated normal distribution:
[[ 0.79916     0.09768514  0.59500927 -0.19671005]
 [-0.3189082   0.40609044 -1.1154413  -0.03526925]
 [ 1.7734306  -0.7746173   0.7038834   1.1636325 ]
 [ 0.88560045  1.1292641   1.3998685   0.9906496 ]]



In [4]:
# 3. Create a matrix C with dimensions 2x2, mean=3, std=0.5
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print(f"Matrix C (2x2) with normal distribution (mean={mean}, stddev={stddev}):")
print(C.numpy())
print()

Matrix C (2x2) with normal distribution (mean=3.0, stddev=0.5):
[[2.7150679 3.1694708]
 [2.8172727 3.1465561]]



In [6]:
import tensorflow as tf

# Define matrices A and B with compatible shapes
A = tf.random.normal(shape=(3, 3))
B = tf.random.normal(shape=(3, 3))

# Perform matrix addition
D = tf.add(A, B)

# Print the result
print("Matrix D (result of A + B):")
print(D.numpy())

Matrix D (result of A + B):
[[ 2.2542472   1.9047005  -0.40600127]
 [ 0.23095673  3.7119427  -0.19339433]
 [-1.2131704  -0.7377082  -0.0730788 ]]


In [14]:
import tensorflow as tf

# Define matrices C and D with compatible shapes
C = tf.random.normal(shape=(2, 3))  # Example: 2x3 matrix
D = tf.random.normal(shape=(3, 4))  # Example: 3x4 matrix

# Perform matrix multiplication
E = tf.matmul(C, D)

# Print the result
print("Matrix E (result of C * D):")
print(E.numpy())

Matrix E (result of C * D):
[[-0.38070095 -0.26633853 -1.3008428   0.7877242 ]
 [ 0.5418619   0.14837825  1.5376445  -0.93297076]]


TASK 2 : PERFORMING ADDITIONAL MATRIX OPERATIONS

1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.
2. Calculate the transpose of matrix F and store the result in matrix G.
3. Calculate the element-wise exponential of matrix F and store the result in matrix Hc
4. Create a matrix I by concatenating matrix F and matrix G horizontallyc
5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [15]:
# 1. Create a matrix F with dimensions 3x3, initialized with random values using random_uniform
import tensorflow as tf
F = tf.random.uniform(shape=(3, 3))
print("Matrix F (3x3) with random uniform distribution:")
print(F.numpy())
print()

Matrix F (3x3) with random uniform distribution:
[[0.54301536 0.71466875 0.26682794]
 [0.27419007 0.29377723 0.44443822]
 [0.01811516 0.46537519 0.96880543]]



In [10]:
# 2. Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)
print("Matrix G (transpose of F):")
print(G.numpy())
print()

Matrix G (transpose of F):
[[0.5800955  0.686044   0.8215511 ]
 [0.7525996  0.1388216  0.24309433]
 [0.90608    0.57082343 0.9230279 ]]



In [11]:
# 3. Calculate the element-wise exponential of matrix F and store the result in matrix H
H = tf.exp(F)
print("Matrix H (element-wise exponential of F):")
print(H.numpy())
print()

Matrix H (element-wise exponential of F):
[[1.7862091 2.1225104 2.4746032]
 [1.9858439 1.1489191 1.7697237]
 [2.2740242 1.2751889 2.5168998]]



In [12]:
# 4. Create a matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (concatenation of F and G horizontally):")
print(I.numpy())
print()

Matrix I (concatenation of F and G horizontally):
[[0.5800955  0.7525996  0.90608    0.5800955  0.686044   0.8215511 ]
 [0.686044   0.1388216  0.57082343 0.7525996  0.1388216  0.24309433]
 [0.8215511  0.24309433 0.9230279  0.90608    0.57082343 0.9230279 ]]



In [13]:
# 5. Create a matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (concatenation of F and H vertically):")
print(J.numpy())

Matrix J (concatenation of F and H vertically):
[[0.5800955  0.7525996  0.90608   ]
 [0.686044   0.1388216  0.57082343]
 [0.8215511  0.24309433 0.9230279 ]
 [1.7862091  2.1225104  2.4746032 ]
 [1.9858439  1.1489191  1.7697237 ]
 [2.2740242  1.2751889  2.5168998 ]]
